DROP PROCEDURE loguear
DROP PROCEDURE agregarConsulta
DROP PROCEDURE GuardarUsuarioSesionActual
DROP PROCEDURE cantidadDeBusquedasPorFecha
DROP PROCEDURE resultadosParciales
DROP PROCEDURE resultadosTotales
DROP PROCEDURE obtenerParametrosBusqueda
DROP PROCEDURE guardarParametrosBusqueda
DROP PROCEDURE obtenerParadas
DROP PROCEDURE obtenerCgps
DROP PROCEDURE obtenerLocales
DROP PROCEDURE obtenerServiciosDeCgp
DROP PROCEDURE obtenerRubrosDeLocal
DROP PROCEDURE obtenerBancos

DROP TABLE Usuarios
DROP TABLE Consultas
DROP TABLE UsuarioSesionActual
DROP TABLE rubros_local
DROP TABLE local
DROP TABLE rubro
DROP TABLE servicios_cgp
DROP TABLE servicio
DROP TABLE cgp
DROP TABLE parada
DROP TABLE poi